name: Build TWRP for SM-T575

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: false
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig openjdk-11-jdk python3
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize TWRP Source Tree
      run: |
        mkdir twrp && cd twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-11 --depth=1
        repo sync -c -j$(nproc) --no-clone-bundle --no-tags --current-branch

    - name: Clone Device Tree
      run: |
        cd twrp
        git clone https://github.com/${{ github.repository }}.git device/samsung/gtactive3

    - name: Compile TWRP
      run: |
        cd twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_gtactive3-eng
        mka recoveryimage -j$(nproc)
        cd out/target/product/gtactive3/
        tar -cvf twrp_SM-T575.tar recovery.img

    - name: Upload TWRP Tar to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TWRP_SM-T575_Odin
        path: twrp/out/target/product/gtactive3/twrp_SM-T575.tar
